"""app.routers.menu — auth-/profil-skyddad GET /api/menu -> 3 suggestions (Phase 7 T6 api-lager, gate C6).

The API-lager's headline endpoint: a logged-in user asks for a week's menu and gets
THREE candidate plans (suggestions), each generated by the Phase 6 ``plan_menu``
optimizer (ratio N5 filter >= 0.5 + 3-seed greedy). It is auth-SKYDDAD and
profil-SKYDDAD:

  * AUTH: every handler first resolves the opaque ``matapp_session`` cookie to a
    logged-in ``users.User`` via Phase 3 ``auth_service.current_user``; absent/invalid
    cookie -> **401, never 200** (the exact gate-C6 line "utan session 401").
  * PROFIL: the suggestion families are built from the authenticated user's own
    persisted profile (persons, meal_days) via Phase 5 ``profile_service.load_profile``
    — so the plan respects THAT user's household, not a hardcoded one. When no profile
    is saved yet we fall back to Phase-6 FamilyPrefs defaults (persons=4, meal_days=5)
    rather than failing the request.

Response is pydantic-validated (gate C6 "pydantic-validering"): the JSON body is
declared as MenuResponse with a list[Suggestion], each suggestion the {seed, week_key,
days[]} shape produced by the Phase 6 Plan.

Single concern: HTTP wire-up + optimizer invocation. Auth/persistence live in the
service modules; plan_menu/offers/recipes in app/optimizer/.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from fastapi import APIRouter, Depends, HTTPException, Request

from app import auth_service, profile_service, security
from app.optimizer import optimizer
from app.optimizer.offers import WEEK_KEY, offers
from app.optimizer.recipes import recipes
from app.models.users import User

router = APIRouter(prefix="/api/menu", tags=["menu"])

# Gate C6 contract: exactly three suggestions (the Phase 6 DEFAULT_SEEDS = 3 seeds).
SUGGESTION_COUNT = 3
RATIO_THRESHOLD = 0.5  # Phase 6 gate C5 hard N5 filter (majority-extrapris).


# ---------------------------------------------------------------------------
# Pydantic response models (gate C6 "pydantic-validering")
# ---------------------------------------------------------------------------


class MenuDay(BaseModel):
    date: str
    dish_id: str
    andel_extrapris: float


class Suggestion(BaseModel):
    week_key: str
    seed: int
    days: list[MenuDay]


class MenuResponse(BaseModel):
    week_key: str
    suggestions: list[Suggestion] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Auth dependency (mirrors app/routers/profile.py — 401, never 200)
# ---------------------------------------------------------------------------


def _current_user_or_401(request: Request) -> User:
    """Resolve the session cookie to a User; 401 when absent/invalid (auth-skyddad)."""
    token = request.cookies.get(security.SESSION_COOKIE)
    user = auth_service.current_user(token)
    if user is None:
        raise HTTPException(status_code=401, detail="not authenticated")
    return user


# ---------------------------------------------------------------------------
# The endpoint
# ---------------------------------------------------------------------------


@router.get("", response_model=MenuResponse)
def get_menu(request: Request,
             user: User = Depends(_current_user_or_401)) -> MenuResponse:
    """A fake suggestion list of length 3 for the authenticated user's household."""

    # PROFIL-skyddad: build the family from THIS user's saved profile.
    profile = profile_service.load_profile(user)
    if profile is not None:
        persons = profile.persons
        meal_days = profile.meal_days
    else:
        persons = optimizer.FamilyPrefs().persons  # Phase 6 default: 4
        meal_days = optimizer.FamilyPrefs().meal_days  # Phase 6 default: 5

    family = optimizer.FamilyPrefs(meal_days=meal_days, persons=persons)
    plans = optimizer.plan_menu(
        WEEK_KEY,
        offers(),
        recipes(),
        family,
        ratio_threshold=RATIO_THRESHOLD,
    )

    # Pydantic validates + shapes the response (gate C6).
    suggestions = [
        Suggestion(
            week_key=p["week_key"],
            seed=p["seed"],
            days=[MenuDay(**d) for d in p["days"]],
        )
        for p in plans[:SUGGESTION_COUNT]
    ]
    return MenuResponse(week_key=WEEK_KEY, suggestions=suggestions)
